### ISSUE TITLE
Update docs pages to use Google Tag Manager

### ISSUE THREAD

**Issue by dogeared** [stormpath/stormpath-sdk-java#1008]
Instructions can be found at: https://stormpath.atlassian.net/browse/MARKETING-2083

Placing them here for those that don't have access:

1) Please place the attached script immediately after the opening `<body>` tag on your repos:
- Spring-Boot integration docs
- Servlet plugin docs
- JavaDocs
- Note: This may now be the unified docs

2) If present, Please remove the Google Analytics and KissMetrics scripts as they are now redundant

3) Please do not remove Optimizely or Zendesk tags if present. These are not served by GTM.

4) Once installed and deployed, please assign issue back to Brent Jensen for review.

Here is the script:

```
<!-- Google Tag Manager -->
<noscript><iframe src="//www.googletagmanager.com/ns.html?id=GTM-NQZZFW"
height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'//www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','GTM-NQZZFW');</script>
<!-- End Google Tag Manager -->
```

**Comment by mzumbadoate** [comment]
this was fixed here 
https://github.com/stormpath/stormpath-sphinx-theme/commit/8fdd37def01968b29155e41ab3f952dd03a99652
by @robertjd 
and then updated by @rdegges

**Comment by brentstormpath** [comment]
@dogeared  Can you please take another look at this issue? It looks like it was closed out because of the global change to the Sphinx docs but I believe that was premature.

The JavaDocs still do not have Google Tag Manager as they are not a Sphinx project.
