### ISSUE TITLE
Fix bug where empty value in key value pair is causing servlet to blow up

### ISSUE THREAD

**Issue by dogeared** [stormpath/stormpath-sdk-java#328]
We recently added properties to `default.stormpath.properties` that don't have values. 

This is explicitly not allowed by the current `DefaultPropertiesParser`

**Comment by mrioan** [comment]
The fix is to change `DefaultPropertiesParser` to allow that or we will be removing `default.stormpath.properties` altogether?

**Comment by dogeared** [comment]
This was addressed by #329

**Comment by lhazlewood** [comment]
I'm confused - all of our config properties start with `stormpath.` by design (so they can be filtered, auto-completed, easily discovered in projects, etc).  Do we still have a `default.stormpath.properties` ?
